language: python
python:
- '2.7'
before_install:
- sudo apt-get install -y silversearcher-ag
install:
- nvm install 8
- nvm use 8
- pip install --upgrade pip
- pip install lektor
- pip install boto3
- pip list
- npm install
- npm run build
- ag yaml
script:
- lektor build
deploy:
  provider: script
  script: lektor deploy s3
  on:
    branch: master
env:
  global:
  - secure: qWNZV+l7x+JjkdYG1tRGaUy3R+ytC5kweUwQyT2iT1Pgd8uUiQkrvIt5SNwVmDdPY0c26u8hRKp2gwolP5Eibj08DB3+WMpVaqpIvtR2x/sc9Urk0uvBhvAIg5ZiiXcQYEUSNKx15NlhzhDt2Fg+eMYa8zqBu7OmwgtJw07seimtk9Hv079uMM5EOdX7TglgxhydVvf9gpKxTpo0uI0R3/WZ6PzYoqeTm6c+93k/GaygNX0wWMlK8iRhHOVhf4fNXvUTCg3Vzoqi3VZcnvp7xKVntYN5GYUkUeisrYIp7RyfvTJG7mxOA8/m8yU0tscj8FlQWHoyeD8HevDtPFg2y2goAh2b2HbTBrrP6uOxbeb+0po3F7Gp1QzMl8zVcEt8WhLsLn7+oDMBdVN56/6yUyUy4Exa0ak/na5dKmRdNws+DKMNDdV0fwopKdfb8MkqB2fTjVfodZyYU5LGqKd5iwzAL63f2pNgq68sYt8+IxSZMU183deTTeQ7sff0pGck946s/w8Y4WGWCCJ6D+aa3/nU9oF8/o/EP4vn0fqEubHXs5K3ibWtOHiodZcEcDXEs2pS1Dxngl7Woc72JBReQdoxpKNCGhDvwMnr1HI2OL01OxzSKBDq3flNtQiTbcS7rlbBgQ3xauDXxBgVUXxiK/eL5hSnAhLH0E/TlBhEUeQ=
  - secure: eAoOhQNADNpvOMq2aK/vc1gRajMDr3QKERgYhztsGNfFJXn+MK5JnY7ClFs23vcdekQ6N7uNP2bqXDdFlEGnOAOfwJNF+SFVNfNI6/tA8DrXFbbOkHwon8P1VrvhtW/FLfrlg7xmupQgNL7V+NbqBulfsmSNNOyas0FJCpF7YvZlZmba8yGmNZeLe2rMXdhCIfNT0zkKArnIPer9Q60/fKIQtoYszv3P9Tk+72YpgkYSDXlqcWxeS/6T9M8zN3LCQrPzHcv9e8z3wT5oL3086ZdL+O7oI92tyEbiDZhnYCDDIrziBtnUry1XENP6H/ml3qs6sAEuC0T2Fk6yEEs1O1xUgsltQv4GaWUhSWYwMgTuh4V6trj/d6tzMIGzJisCN8mnGl+14illGHez6Ibq8O0YcKA7MS2jaoa6nfnRWIT4QC3oE/vSB8Oa5Ryj/u3J+bFP6sMn8ObaCdAkhPoFbUJ1BOIbQyUzQ2p9TXPO11WQgNI9FWEsiDRji39tJvew5bdLmw5ljgDlwasgFxf+rUg2WIHJYn/aYLbY+fQaaOrrQ7xjmoCnCBicgG0nj5tbyd9WljmeOvPIK8Ju8V8r0iH8Zrjc2oxPdSzRZjb10z4AMkiOOyTILvqMuAMk1sElqjyJKiTncG1vD2FUT2IPZvglZrgL6Qg8tKpJ9y5TJkY=
  - secure: YBPSl1zCexzsrK7tFsOeFmTy9hssmL2e/k7tbxIvDWd8kjso+PTGqxPZZVxzncR2lH0QlHr+iCs/W0Sc5XZoYkssUcLIUNClgOzjpxtqTTQN9jrRnyl5hbx3fAKoXbYmyTrnR1RvrBUK1ioONYLR+GmUWSKNEDvMNQUoUIPOsXlvTxVUIb1GwHef4xlsdnROajoAqyb7KavAJ+SqXfzCEkHWOBGiHq4Zf8vKWBf2nC8I9oYCEm32rkfCQc4KAcqVJcLLiYRqf1N+SP/9Ynze9qrznABYsJyrB9/gF9JfLZgNf/uwf/3hnckxr+1XeMU2AGE7upt7gxpd+EGiH6zJlr5M4/uU/aJqftzgDZblWA2xSR7q/me85vd6dDt1iQGceHzU+QCpC1AogbvVccvTXBMDRfcFL1qBaVBS0NPPO4CQJKOxsnK85IstDSLpPHV/9kJLHiaNUb6ra5AdKnIztfkyNSmkcMDflZrAFKx20I+7EFm6O1AplqyR7AJk1KC6utm7X7psiipFjF3YTVnRQVO+OFbKyGgGNOlcnhn3sC/JKvbUfTguQwUMEivkcGZ3shP6hYcbm4i4LGmjtThWSjG1sydOOZVXkrqpxbLWQxt05GM1muexeEWrAyidTq5XN5b7ujeRijyqdip5+5kQGiK98Ki7oWu1xK9ZRXbR9Kg=
