# Site settings
title: Frictionless Data
short_title: Frictionless Data
description: |
  Lightweight standards and tooling to make it effortless to get, share, and validate data.
baseurl: ""
url: "http://frictionlessdata.io" # the base hostname & protocol for your site
github_username:  frictionlessdata
github_repo:  frictionlessdata.io
paypal: admin@okfn.org
contact: http://discuss.okfn.org/c/frictionless-data
editsitehowto: /about/edit-site/
gems:
  - jekyll-redirect-from

supporters:
  -
    name: Sloan Foundation
    logo: sloan.png
    footer_logo: sloan-footer.png
    url: http://www.sloan.org/
  -
    name: Google
    logo: google.png
    footer_logo: google-footer.png
    url: http://www.google.org/

googleanalytics: UA-33874954-38

markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true


permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: page
      edit: true
  -
    scope:
      path: "standards"
    values:
      section: standards
  -
    scope:
      path: "tools"
    values:
      section: tools
  -
    scope:
      path: "guides"
    values:
      section: guides
  -
    scope:
      path: ""
      type: "case_studies"
    values:
      section: case-studies
      layout: case_study
      lead: true

related_projects:
  -
      name: OpenGovernmentData.org
      link: http://opengovernmentdata.org/
  -
      name: The DataHub
      link: http://datahub.io/
  -
      name: DataCatalogs.org
      link: http://datacatalogs.org/
  -
      name: OpenSpending.org
      link: http://openspending.org/
  -
      name: SchoolOfData.org
      link: http://schoolofdata.org/
  -
      name: OpenDefinition.org
      link: http://opendefinition.org/
  -
      name: Introducing Open Data
      link: http://okfn.org/opendata/

collections:
  case_studies:
    output: true
    permalink: /case-studies/:path/